---
- hosts: "{{ target }}"
  gather_facts: false
  remote_user: root
  roles:
   - role: debian11-fix
     when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "11")